### PR TITLE
paper 3

### PR DESCRIPTION
**Pull request by neelkshah**

### CODE REVIEW

**Comment by twitu** [comment]
Will you be answering the next-key locking question in this PR?

**Comment by neelkshah** [comment]
Will do it in the next PR. By then if this one is not reviewed, I'll add it here

**Review by twitu — APPROVED** [review]
Nicely summarized

**Comment by neelkshah** [comment]
Added the next-key locking answer. @twitu do review since it was your question. @shubh-ranade assigning PR to you. Please review and merge.

**Review by twitu — APPROVED** [review]

**Review by shubh-ranade — APPROVED** [review]

**Pull request merged**
